package repo

// Code generated by crud-gen. DO NOT EDIT.

import (
	"crud-gen/models"
	"database/sql"
	"errors"
	"fmt"
)

// ── Sentinel errors ───────────────────────────────────────────────────────────

var (
	ErrUserNotFound  = errors.New("users: record not found")
	ErrUserNilModel  = errors.New("users: model is nil")
	ErrUserInvalidID = errors.New("users: id must be > 0")
)

// ── Interface ─────────────────────────────────────────────────────────────────

// UserRepository defines data-access operations for User.
type UserRepository interface {
	Create(m *models.User) error
	Get(id int) (*models.User, error)
	Update(id int, m *models.User) error
	Delete(id int) error
	List(limit, offset int) ([]*models.User, error)
}

// ── Implementation ────────────────────────────────────────────────────────────

type uRepository struct{ db *sql.DB }

// NewUserRepository constructs a UserRepository backed by db.
func NewUserRepository(db *sql.DB) UserRepository {
	return &uRepository{db: db}
}

// Create inserts a new User row and populates m.ID from RETURNING.
func (r *uRepository) Create(m *models.User) error {
	if m == nil {
		return ErrUserNilModel
	}
	const q = `INSERT INTO users (name, email, age, created_at, updated_at, bio)
		VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`
	return r.db.QueryRow(q, m.Name, m.Email, m.Age, m.CreatedAt, m.UpdatedAt, m.Bio).Scan(&m.ID)
}

// Get fetches a single User by primary key.
func (r *uRepository) Get(id int) (*models.User, error) {
	if id <= 0 {
		return nil, ErrUserInvalidID
	}
	const q = `SELECT id, name, email, age, created_at, updated_at, bio FROM users WHERE id = $1`
	m := &models.User{}
	err := r.db.QueryRow(q, id).Scan(&m.ID, &m.Name, &m.Email, &m.Age, &m.CreatedAt, &m.UpdatedAt, &m.Bio)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrUserNotFound
	}
	return m, err
}

// Update replaces all mutable columns for the given id.
func (r *uRepository) Update(id int, m *models.User) error {
	if id <= 0 {
		return ErrUserInvalidID
	}
	if m == nil {
		return ErrUserNilModel
	}
	const q = `UPDATE users SET name = $1, email = $2, age = $3, created_at = $4, updated_at = $5, bio = $6 WHERE id = $7`
	res, err := r.db.Exec(q, m.Name, m.Email, m.Age, m.CreatedAt, m.UpdatedAt, m.Bio, id)
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrUserNotFound
	}
	return nil
}

// Delete removes the User with the given id.
func (r *uRepository) Delete(id int) error {
	if id <= 0 {
		return ErrUserInvalidID
	}
	const q = `DELETE FROM users WHERE id = $1`
	res, err := r.db.Exec(q, id)
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrUserNotFound
	}
	return nil
}

// List returns paginated User rows ordered by ID.
// limit=0 disables the LIMIT clause.
func (r *uRepository) List(limit, offset int) ([]*models.User, error) {
	if limit < 0 || offset < 0 {
		return nil, fmt.Errorf("users: limit and offset must be >= 0")
	}
	q := `SELECT id, name, email, age, created_at, updated_at, bio FROM users ORDER BY id`
	if limit > 0 {
		q += fmt.Sprintf(" LIMIT %d OFFSET %d", limit, offset)
	}
	rows, err := r.db.Query(q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []*models.User
	for rows.Next() {
		m := &models.User{}
		if err := rows.Scan(&m.ID, &m.Name, &m.Email, &m.Age, &m.CreatedAt, &m.UpdatedAt, &m.Bio); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, rows.Err()
}
