package repo

// Code generated by crud-gen. DO NOT EDIT.

import (
	"database/sql"
	"os"
	"testing"

	_ "github.com/lib/pq"
)

func openTestDB(t *testing.T) *sql.DB {
	t.Helper()
	dsn := os.Getenv("TEST_DB_URL")
	if dsn == "" {
		t.Skip("TEST_DB_URL not set")
	}
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	if err := db.Ping(); err != nil {
		t.Fatalf("ping db: %v", err)
	}
	t.Cleanup(func() { db.Close() })
	return db
}

func TestUserRepository_Create(t *testing.T) {
	db := openTestDB(t)
	repo := NewUserRepository(db)
	if err := repo.Create(nil); err == nil {
		t.Fatal("want error for nil model")
	}
}

func TestUserRepository_Get(t *testing.T) {
	db := openTestDB(t)
	repo := NewUserRepository(db)
	if _, err := repo.Get(0); err == nil {
		t.Fatal("want error for id=0")
	}
	if _, err := repo.Get(-1); err == nil {
		t.Fatal("want error for id=-1")
	}
}

func TestUserRepository_Update(t *testing.T) {
	db := openTestDB(t)
	repo := NewUserRepository(db)
	if err := repo.Update(0, nil); err == nil {
		t.Fatal("want error for id=0")
	}
}

func TestUserRepository_Delete(t *testing.T) {
	db := openTestDB(t)
	repo := NewUserRepository(db)
	if err := repo.Delete(0); err == nil {
		t.Fatal("want error for id=0")
	}
}

func TestUserRepository_List(t *testing.T) {
	db := openTestDB(t)
	repo := NewUserRepository(db)
	if _, err := repo.List(-1, 0); err == nil {
		t.Fatal("want error for limit=-1")
	}
}
