// Package templates holds text/template source for CRUD generation.
// All SQL assembly is done in generator/data.go — templates stay simple.
package templates

// Repository generates the repository implementation file.
const Repository = `package {{.Package}}

// Code generated by crud-gen. DO NOT EDIT.

import (
	"database/sql"
	"errors"
	"fmt"
{{- if .ModelImport}}
	{{printf "%q" .ModelImport}}
{{- end}}
)

// ── Sentinel errors ───────────────────────────────────────────────────────────

var (
	Err{{.ModelName}}NotFound  = errors.New("{{.TableName}}: record not found")
	Err{{.ModelName}}NilModel  = errors.New("{{.TableName}}: model is nil")
	Err{{.ModelName}}InvalidID = errors.New("{{.TableName}}: id must be > 0")
)

// ── Interface ─────────────────────────────────────────────────────────────────

// {{.ModelName}}Repository defines data-access operations for {{.ModelName}}.
type {{.ModelName}}Repository interface {
	Create(m *{{.ModelRef}}) error
	Get(id int) (*{{.ModelRef}}, error)
	Update(id int, m *{{.ModelRef}}) error
	Delete(id int) error
	List(limit, offset int) ([]*{{.ModelRef}}, error)
}

// ── Implementation ────────────────────────────────────────────────────────────

type {{.ReceiverName}}Repository struct{ db *sql.DB }

// New{{.ModelName}}Repository constructs a {{.ModelName}}Repository backed by db.
func New{{.ModelName}}Repository(db *sql.DB) {{.ModelName}}Repository {
	return &{{.ReceiverName}}Repository{db: db}
}

// Create inserts a new {{.ModelName}} row and populates m.{{.IDField}}.
func (r *{{.ReceiverName}}Repository) Create(m *{{.ModelRef}}) error {
	if m == nil {
		return Err{{.ModelName}}NilModel
	}
{{- if .UseReturning}}
	const q = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertColumns}})
		VALUES ({{.InsertPlaceholders}}) RETURNING {{.IDColumn}}` + "`" + `
	return r.db.QueryRow(q, {{.InsertArgs}}).Scan(&m.{{.IDField}})
{{- else}}
	const q = ` + "`" + `INSERT INTO {{.TableName}} ({{.InsertColumns}}) VALUES ({{.InsertPlaceholders}})` + "`" + `
	res, err := r.db.Exec(q, {{.InsertArgs}})
	if err != nil {
		return err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}
	m.{{.IDField}} = int(id)
	return nil
{{- end}}
}

// Get fetches a single {{.ModelName}} by primary key.
func (r *{{.ReceiverName}}Repository) Get(id int) (*{{.ModelRef}}, error) {
	if id <= 0 {
		return nil, Err{{.ModelName}}InvalidID
	}
	const q = ` + "`" + `SELECT {{.SelectColumns}} FROM {{.TableName}} WHERE {{.IDColumn}} = {{.SingleParam}}` + "`" + `
	m := &{{.ModelRef}}{}
	err := r.db.QueryRow(q, id).Scan({{.ScanArgs}})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, Err{{.ModelName}}NotFound
	}
	return m, err
}

// Update replaces all mutable columns for the given id.
func (r *{{.ReceiverName}}Repository) Update(id int, m *{{.ModelRef}}) error {
	if id <= 0 {
		return Err{{.ModelName}}InvalidID
	}
	if m == nil {
		return Err{{.ModelName}}NilModel
	}
	const q = ` + "`" + `UPDATE {{.TableName}} SET {{.SetClause}} WHERE {{.IDColumn}} = {{.UpdateWhere}}` + "`" + `
	res, err := r.db.Exec(q, {{.UpdateArgs}})
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return Err{{.ModelName}}NotFound
	}
	return nil
}

// Delete removes the {{.ModelName}} with the given id.
func (r *{{.ReceiverName}}Repository) Delete(id int) error {
	if id <= 0 {
		return Err{{.ModelName}}InvalidID
	}
	const q = ` + "`" + `DELETE FROM {{.TableName}} WHERE {{.IDColumn}} = {{.SingleParam}}` + "`" + `
	res, err := r.db.Exec(q, id)
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return Err{{.ModelName}}NotFound
	}
	return nil
}

// List returns paginated {{.ModelName}} rows ordered by {{.IDField}}.
// limit=0 disables the LIMIT clause.
func (r *{{.ReceiverName}}Repository) List(limit, offset int) ([]*{{.ModelRef}}, error) {
	if limit < 0 || offset < 0 {
		return nil, fmt.Errorf("{{.TableName}}: limit and offset must be >= 0")
	}
	q := ` + "`" + `SELECT {{.SelectColumns}} FROM {{.TableName}} ORDER BY {{.IDColumn}}` + "`" + `
	if limit > 0 {
		q += fmt.Sprintf(" LIMIT %d OFFSET %d", limit, offset)
	}
	rows, err := r.db.Query(q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []*{{.ModelRef}}
	for rows.Next() {
		m := &{{.ModelRef}}{}
		if err := rows.Scan({{.ScanArgs}}); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, rows.Err()
}
`

// Test generates *_test.go with basic boundary-condition tests.
const Test = `package {{.Package}}

// Code generated by crud-gen. DO NOT EDIT.

import (
	"database/sql"
	"os"
	"testing"
{{- if .DriverImport}}

	_ {{printf "%q" .DriverImport}}
{{- end}}
)

func openTestDB(t *testing.T) *sql.DB {
	t.Helper()
	dsn := os.Getenv("TEST_DB_URL")
	if dsn == "" {
		t.Skip("TEST_DB_URL not set")
	}
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	if err := db.Ping(); err != nil {
		t.Fatalf("ping db: %v", err)
	}
	t.Cleanup(func() { db.Close() })
	return db
}

func Test{{.ModelName}}Repository_Create(t *testing.T) {
	db := openTestDB(t)
	repo := New{{.ModelName}}Repository(db)
	if err := repo.Create(nil); err == nil {
		t.Fatal("want error for nil model")
	}
}

func Test{{.ModelName}}Repository_Get(t *testing.T) {
	db := openTestDB(t)
	repo := New{{.ModelName}}Repository(db)
	if _, err := repo.Get(0); err == nil {
		t.Fatal("want error for id=0")
	}
	if _, err := repo.Get(-1); err == nil {
		t.Fatal("want error for id=-1")
	}
}

func Test{{.ModelName}}Repository_Update(t *testing.T) {
	db := openTestDB(t)
	repo := New{{.ModelName}}Repository(db)
	if err := repo.Update(0, nil); err == nil {
		t.Fatal("want error for id=0")
	}
}

func Test{{.ModelName}}Repository_Delete(t *testing.T) {
	db := openTestDB(t)
	repo := New{{.ModelName}}Repository(db)
	if err := repo.Delete(0); err == nil {
		t.Fatal("want error for id=0")
	}
}

func Test{{.ModelName}}Repository_List(t *testing.T) {
	db := openTestDB(t)
	repo := New{{.ModelName}}Repository(db)
	if _, err := repo.List(-1, 0); err == nil {
		t.Fatal("want error for limit=-1")
	}
}
`
